version: '3.7'

services:
  app:
    container_name: app
    image: app_image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "8000:8000"
    depends_on:
      app_db:
        condition: service_healthy

  app_db:
    container_name: app_db
    hostname: app_db
    image: library/postgres:14.1
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - app_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "app"]
      interval: 1s
      timeout: 1s
      retries: 5

volumes:
  app_pg_data:
    driver: "local"

networks:
  default:
    name: app_main
